kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exascaler-csi-privileged-scc-role
rules:
  - apiGroups: [ "security.openshift.io" ]
    resources: [ "securitycontextconstraints" ]
    resourceNames: [ "privileged" ]
    verbs: [ "use" ]
