kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exascaler-csi-node-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: exascaler-csi-node-service-account
    namespace: placeholder
roleRef:
  kind: ClusterRole
  name: exascaler-csi-node-cluster-role
  apiGroup: rbac.authorization.k8s.io
