apiVersion: charts.my.domain/v1alpha1
kind: ExaCsi
metadata:
  name: exacsi-sample
spec:
  # Default values copied from <project_dir>/helm-charts/exa-csi/values.yaml
  image:
    pullPolicy: Always
    repository: quay.io/ddn/exascaler-csi-file-driver
    tag: master
  namespace: exa-csi-driver-operator-system
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  secretName: exascaler-csi-file-driver-config
  volumeNamePrefix: pvc-exa
  
  
